"""Generated by Django 5.2.5 on 2025-09-06 17:03"""

# Third-party imports
from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates the `url` field to accommodate the de facto length of a URL."""

    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedproject",
            name="url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
