"""Generated by Django 5.2.5 on 2025-10-10 21:44"""

# Third-party imports
from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates the `ExtractedProject` model to include the `fiscal_year_effective` field."""

    dependencies = [
        ("extract", "0002_alter_extractedproject_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedproject",
            name="fiscal_year_effective",
            field=models.TextField(blank=True, default=""),
        ),
    ]
