# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestForm13FInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cik', models.CharField(db_column='company_cik', max_length=10)),
                ('company_name', models.TextField(db_column='company_name')),
                ('form_accession_number', models.TextField(db_column='form_accession_number')),
                ('form_report_period', models.DateField(db_column='form_report_period')),
                ('form_filing_date', models.DateField(db_column='form_filing_date', null=True)),
                ('form_acceptance_date', models.DateField(db_column='form_acceptance_date', null=True)),
                ('form_effective_date', models.DateField(db_column='form_effective_date', null=True)),
                ('form_url', models.URLField(db_column='form_url')),
                ('exchange_code', models.TextField(db_column='exchange_code', null=True)),
                ('issuer_name', models.TextField(db_column='issuer_name')),
                ('cusip', models.CharField(db_column='cusip', max_length=9)),
                ('title_class', models.TextField(db_column='title_class', null=True)),
                ('market_sector', models.CharField(db_column='market_sector', max_length=255)),
                ('security_type', models.CharField(db_column='security_type', max_length=255)),
                ('ticker', models.CharField(db_column='ticker', max_length=255)),
                ('value_x1000', models.IntegerField(db_column='value_x1000')),
                ('shares_prn_amt', models.IntegerField(db_column='shares_prn_amt')),
                ('sh_prn', models.CharField(db_column='sh_prn', max_length=255)),
                ('put_call', models.TextField(db_column='put_call', null=True)),
                ('investment_discretion', models.CharField(db_column='investment_discretion', max_length=255)),
                ('manager', models.TextField(blank=True, db_column='manager', default='')),
                ('voting_auth_sole', models.IntegerField(db_column='voting_auth_sole', null=True)),
                ('voting_auth_shared', models.IntegerField(db_column='voting_auth_shared', null=True)),
                ('voting_auth_none', models.IntegerField(db_column='voting_auth_none', null=True)),
                ('num_shares', models.IntegerField(db_column='num_shares')),
                ('principal_amount', models.IntegerField(db_column='principal_amount')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'form_13f_investment_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form13FCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(db_column='cik', max_length=10)),
                ('name', models.TextField(db_column='name')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'form_13f_company',
            },
        ),
        migrations.CreateModel(
            name='Form13FSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('accession_number', models.TextField(db_column='accession_number')),
                ('report_period', models.DateField(db_column='report_period')),
                ('filing_date', models.DateField(db_column='filing_date', null=True)),
                ('acceptance_date', models.DateField(db_column='acceptance_date', null=True)),
                ('effective_date', models.DateField(db_column='effective_date', null=True)),
                ('url', models.URLField(db_column='url')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='form13f.form13fcompany')),
            ],
            options={
                'db_table': 'form_13f_submission',
            },
        ),
        migrations.CreateModel(
            name='Form13FInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.TextField(db_column='exchange_code', null=True)),
                ('issuer_name', models.TextField(db_column='issuer_name')),
                ('cusip', models.CharField(db_column='cusip', max_length=9)),
                ('title_class', models.TextField(db_column='title_class', null=True)),
                ('market_sector', models.CharField(db_column='market_sector', max_length=255)),
                ('security_type', models.CharField(db_column='security_type', max_length=255)),
                ('ticker', models.CharField(db_column='ticker', max_length=255)),
                ('value_x1000', models.IntegerField(db_column='value_x1000')),
                ('shares_prn_amt', models.IntegerField(db_column='shares_prn_amt')),
                ('sh_prn', models.CharField(db_column='sh_prn', max_length=255)),
                ('put_call', models.TextField(db_column='put_call', null=True)),
                ('investment_discretion', models.CharField(db_column='investment_discretion', max_length=255)),
                ('manager', models.TextField(blank=True, db_column='manager', default='')),
                ('voting_auth_sole', models.IntegerField(db_column='voting_auth_sole', null=True)),
                ('voting_auth_shared', models.IntegerField(db_column='voting_auth_shared', null=True)),
                ('voting_auth_none', models.IntegerField(db_column='voting_auth_none', null=True)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('form', models.ForeignKey(db_column='form', on_delete=django.db.models.deletion.CASCADE, to='form13f.form13fsubmission')),
            ],
            options={
                'db_table': 'form_13f_investment',
            },
        ),
        migrations.AddIndex(
            model_name='form13fcompany',
            index=models.Index(fields=['cik'], name='form_13f_co_cik_af4c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='form13fcompany',
            index=models.Index(fields=['name'], name='form_13f_co_name_3bca96_idx'),
        ),
        migrations.AddConstraint(
            model_name='form13fcompany',
            constraint=models.CheckConstraint(check=models.Q(('cik__length', 10)), name='company_cik_standard_length'),
        ),
        migrations.AddConstraint(
            model_name='form13fcompany',
            constraint=models.UniqueConstraint(fields=('cik', 'name'), name='unique_company_cik'),
        ),
        migrations.AddIndex(
            model_name='form13fsubmission',
            index=models.Index(fields=['accession_number'], name='form_13f_su_accessi_dfad77_idx'),
        ),
        migrations.AddIndex(
            model_name='form13fsubmission',
            index=models.Index(fields=['report_period'], name='form_13f_su_report__eecbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='form13fsubmission',
            index=models.Index(fields=['filing_date'], name='form_13f_su_filing__7794bd_idx'),
        ),
        migrations.AddIndex(
            model_name='form13fsubmission',
            index=models.Index(fields=['acceptance_date'], name='form_13f_su_accepta_41d848_idx'),
        ),
        migrations.AddIndex(
            model_name='form13fsubmission',
            index=models.Index(fields=['effective_date'], name='form_13f_su_effecti_705e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='form13fsubmission',
            constraint=models.UniqueConstraint(fields=('accession_number',), name='unique_form_accession_number'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['issuer_name'], name='form_13f_in_issuer__0ea667_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['exchange_code'], name='form_13f_in_exchang_60ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['cusip'], name='form_13f_in_cusip_947179_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['title_class'], name='form_13f_in_title_c_4e5030_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['market_sector'], name='form_13f_in_market__9c4840_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['security_type'], name='form_13f_in_securit_fb67f6_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['ticker'], name='form_13f_in_ticker_a0880b_idx'),
        ),
        migrations.AddIndex(
            model_name='form13finvestment',
            index=models.Index(fields=['investment_discretion'], name='form_13f_in_investm_77d06c_idx'),
        ),
        migrations.AddConstraint(
            model_name='form13finvestment',
            constraint=models.UniqueConstraint(fields=('form', 'cusip', 'investment_discretion', 'manager'), name='unique_form13f_investment'),
        ),
    ]
