# Generated by Django 5.2.5 on 2025-08-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('started_at_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at_utc', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'extraction_job',
                'constraints': [models.UniqueConstraint(fields=('date',), name='unique_date')],
            },
        ),
        migrations.CreateModel(
            name='ExtractionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Error', 'Error')], default='Not Started', max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(max_length=255)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('started_at_utc', models.DateTimeField(null=True)),
                ('completed_at_utc', models.DateTimeField(null=True)),
                ('failed_at_utc', models.DateTimeField(null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('url', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.extractionjob')),
            ],
            options={
                'db_table': 'extraction_task',
            },
        ),
        migrations.CreateModel(
            name='ExtractedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at_utc', models.DateTimeField(auto_now=True)),
                ('affiliates', models.TextField(blank=True, default='')),
                ('countries', models.TextField(blank=True, default='')),
                ('date_actual_close', models.TextField(blank=True, default='')),
                ('date_approved', models.TextField(blank=True, default='')),
                ('date_disclosed', models.TextField(blank=True, default='')),
                ('date_effective', models.TextField(blank=True, default='')),
                ('date_last_updated', models.TextField(blank=True, default='')),
                ('date_planned_close', models.TextField(blank=True, default='')),
                ('date_planned_effective', models.TextField(blank=True, default='')),
                ('date_revised_close', models.TextField(blank=True, default='')),
                ('date_signed', models.TextField(blank=True, default='')),
                ('date_under_appraisal', models.TextField(blank=True, default='')),
                ('finance_types', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='')),
                ('number', models.CharField(blank=True, default='', max_length=255)),
                ('sectors', models.TextField(blank=True, default='')),
                ('source', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_amount_currency', models.CharField(blank=True, default='', max_length=50)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('url', models.URLField(blank=True, default='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.extractiontask')),
            ],
            options={
                'db_table': 'extracted_project',
            },
        ),
        migrations.AddConstraint(
            model_name='extractiontask',
            constraint=models.UniqueConstraint(fields=('job', 'source', 'workflow_type', 'url'), name='unique_source_url'),
        ),
        migrations.AddConstraint(
            model_name='extractedproject',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='unique_extracted_project'),
        ),
    ]
