# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('iso_code', models.TextField(db_column='iso_code')),
                ('geojson', models.TextField(db_column='geojson')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
