# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='projects',
            field=models.ManyToManyField(through='projects.ProjectCountry', to='projects.Project'),
        ),
    ]
