# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(db_column='number', null=True)),
                ('name', models.TextField(db_column='name', null=True)),
                ('status', models.CharField(db_column='status', max_length=50, null=True)),
                ('year', models.SmallIntegerField(db_column='year', null=True)),
                ('month', models.SmallIntegerField(db_column='month', null=True)),
                ('day', models.SmallIntegerField(db_column='day', null=True)),
                ('loan_amount', models.FloatField(db_column='loan_amount', null=True)),
                ('loan_amount_currency', models.CharField(db_column='loan_amount_currency', max_length=50, null=True)),
                ('loan_amount_in_usd', models.FloatField(db_column='loan_amount_in_usd', null=True)),
                ('sector_list_raw', models.TextField(db_column='sector_list_raw', null=True)),
                ('sector_list_stnd', models.TextField(db_column='sector_list_stnd', null=True)),
                ('country_list_raw', models.TextField(db_column='country_list_raw', null=True)),
                ('country_list_stnd', models.TextField(db_column='country_list_stnd', null=True)),
                ('companies', models.TextField(db_column='companies', null=True)),
                ('url', models.TextField(db_column='url', null=True)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('last_updated_utc', models.DateTimeField(db_column='last_updated_utc', null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'project_country',
            },
        ),
        migrations.CreateModel(
            name='ProjectSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_sector',
            },
        ),
    ]
