# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('banks', '0001_initial'),
        ('countries', '0002_country_projects'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsector',
            name='sector',
            field=models.ForeignKey(db_column='sector', on_delete=django.db.models.deletion.CASCADE, to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='projectcountry',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AddField(
            model_name='projectcountry',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='bank',
            field=models.ForeignKey(db_column='bank', on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
        migrations.AddConstraint(
            model_name='projectsector',
            constraint=models.UniqueConstraint(fields=('project', 'sector'), name='unique_project_sector'),
        ),
        migrations.AddConstraint(
            model_name='projectcountry',
            constraint=models.UniqueConstraint(fields=('project', 'country'), name='unique_project_country'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('bank', 'url'), name='unique_bank_url'),
        ),
    ]
