"""Constants used throughout the application.
"""

from pathlib import Path

# I/O OPERATIONS
ROOT_DIR_PATH = Path(__file__).parent
TEMP_DOWNLOAD_DIR_PATH = "/tmp"
LOCAL_STORAGE_DIR_PATH = f"{ROOT_DIR_PATH}/data"
TESTS_DIR_PATH = f"{ROOT_DIR_PATH}/tests"
SCRAPERS_DIR_PATH = f"{ROOT_DIR_PATH}/scrapers"
CONFIG_DIR_PATH = f"{ROOT_DIR_PATH}/config"
COUNTRIES_FPATH = f"{CONFIG_DIR_PATH}/countries.json"
COUNTRY_CODES_FPATH = f"{CONFIG_DIR_PATH}/country_codes.csv"
CURRENCY_CODES_FPATH = f"{CONFIG_DIR_PATH}/currency_codes.csv"
USER_AGENT_HEADERS_FPATH = f"{CONFIG_DIR_PATH}/user_agent_headers.json"
FORM_13F_COMPANY_FPATH = f"{CONFIG_DIR_PATH}/form13f_companies.json"

# ENVIRONMENT VARIABLES
API_BASE_URL = "API_BASE_URL"
ENV = "ENV"
FRED_API_BASE_URL = "FRED_API_BASE_URL"
FRED_API_KEY = "FRED_API_KEY"
OPEN_FIGI_API_BASE_URL = "OPEN_FIGI_API_BASE_URL"
OPEN_FIGI_API_KEY = "OPEN_FIGI_API_KEY"
OPEN_FIGI_MAX_JOBS_PER_REQUEST = "OPEN_FIGI_MAX_JOBS_PER_REQUEST"
OPEN_FIGI_MAX_REQUESTS_PER_WINDOW = "OPEN_FIGI_MAX_REQUESTS_PER_WINDOW"
OPEN_FIGI_REQUEST_WINDOW_SECONDS = "OPEN_FIGI_REQUEST_WINDOW_SECONDS"

# DEVELOPMENT ENVIRONMENTS
DEV = "dev"
PROD = "prod"

# DATABASE
DEFAULT_BATCH_SIZE = 1000

# FLASK
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5000

# WORKFLOW STATUS
NOT_STARTED_STATUS = "Not Started"
IN_PROGRESS_STATUS = "In Progress"
ERROR_STATUS = "Error"
COMPLETED_STATUS = "Completed"

# WORKFLOW TYPE
DOWNLOAD_WORKFLOW = "project-download"
DYNAMIC_WORKFLOW = "dynamic"
FORM_13F_ARCHIVED_HISTORY_WORKFLOW = "archived-form-history-scrape"
FORM_13F_HISTORY_WORKFLOW = "form-history-scrape"
FORM_13F_WORKFLOW = "form-scrape"
PROJECT_PAGE_WORKFLOW = "project-page-scrape"
PROJECT_PARTIAL_PAGE_WORKFLOW = "project-partial-page-scrape"
RESULTS_PAGE_MULTISCRAPE_WORKFLOW = "results-page-multiscrape"
RESULTS_PAGE_WORKFLOW = "results-page-scrape"
SEED_URLS_WORKFLOW = "seed-urls"

# JOB TYPE
DEV_BANK_PROJECTS_JOB_TYPE = "projects"
FORM_13F_JOB_TYPE = "form13f"

# BANK ABBREVIATIONS
ADB_ABBREVIATION = "adb"
AFDB_ABBREVIATION = "afdb"
AIIB_ABBREVIATION = "aiib"
BIO_ABBREVIATION = "bio"
DEG_ABBREVIATION = "deg"
DFC_ABBREVIATION = "dfc"
EBRD_ABBREVIATION = "ebrd"
EIB_ABBREVIATION = "eib"
FMO_ABBREVIATION = "fmo"
IDB_ABBREVIATION = "idb"
IFC_ABBREVIATION = "ifc"
KFW_ABBREVIATION = "kfw"
MIGA_ABBREVIATION = "miga"
NBIM_ABBREVIATION = "nbim"
PRO_ABBREVIATION = "pro"
UNDP_ABBREVIATION = "undp"
WB_ABBREVIATION = "wb"

# FORM ABBREVIATIONS
FORM_13F_ABBREVIATION = "13F-HR"
