# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('projects', models.ManyToManyField(through='projects.ProjectSector', to='projects.Project')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_sector'),
        ),
    ]
