"""Constants used throughout the application.
"""

import os

# I/O OPERATIONS
SCRAPERS_DIR_PATH = os.path.dirname(os.path.abspath(__file__))
CONFIG_DIR_PATH = f'{SCRAPERS_DIR_PATH}/config'
USER_AGENT_HEADERS_FPATH = f'{CONFIG_DIR_PATH}/user_agent_headers.json'

# ENVIRONMENT VARIABLES
API_BASE_URL = 'API_BASE_URL'
ENV = 'ENV'
DEFAULT_HOST = '0.0.0.0'
DEFAULT_PORT = 5000

# DEVELOPMENT ENVIRONMENTS
DEV_ENV = 'dev'
PROD_ENV = 'prod'

# DATABASE
DEFAULT_BATCH_SIZE = 1000

# WORKFLOW STATUS
NOT_STARTED_STATUS = 'Not Started'
IN_PROGRESS_STATUS = 'In Progress'
ERROR_STATUS = 'Error'
COMPLETED_STATUS = 'Completed'

# WORKFLOW TYPE
DOWNLOAD_WORKFLOW = 'project-download'
DYNAMIC_WORKFLOW = 'dynamic'
PROJECT_PAGE_WORKFLOW = 'project-page-scrape'
PROJECT_PARTIAL_PAGE_WORKFLOW = 'project-partial-page-scrape'
RESULTS_PAGE_MULTISCRAPE_WORKFLOW = 'results-page-multiscrape'
RESULTS_PAGE_WORKFLOW = 'results-page-scrape'
SEED_URLS_WORKFLOW = 'seed-urls'

# JOB TYPE
DEV_BANK_PROJECTS_JOB_TYPE = 'projects'

# BANK ABBREVIATIONS
ADB_ABBREVIATION = 'adb'
AFDB_ABBREVIATION = 'afdb'
AIIB_ABBREVIATION = 'aiib'
BIO_ABBREVIATION = 'bio'
DEG_ABBREVIATION = 'deg'
DFC_ABBREVIATION = 'dfc'
EBRD_ABBREVIATION = 'ebrd'
EIB_ABBREVIATION = 'eib'
FMO_ABBREVIATION = 'fmo'
IDB_ABBREVIATION = 'idb'
IFC_ABBREVIATION = 'ifc'
KFW_ABBREVIATION = 'kfw'
MIGA_ABBREVIATION = 'miga'
NBIM_ABBREVIATION = 'nbim'
PRO_ABBREVIATION = 'pro'
UNDP_ABBREVIATION = 'undp'
WB_ABBREVIATION = 'wb'

# INITIAL WORKFLOW MAPPING
STARTER_WORKFLOWS = {
    ADB_ABBREVIATION : SEED_URLS_WORKFLOW,
    AFDB_ABBREVIATION : SEED_URLS_WORKFLOW,
    AIIB_ABBREVIATION : SEED_URLS_WORKFLOW,
    BIO_ABBREVIATION : SEED_URLS_WORKFLOW,
    DEG_ABBREVIATION : DOWNLOAD_WORKFLOW,
    DFC_ABBREVIATION : DOWNLOAD_WORKFLOW,
    EBRD_ABBREVIATION : SEED_URLS_WORKFLOW,
    EIB_ABBREVIATION : SEED_URLS_WORKFLOW,
    FMO_ABBREVIATION : SEED_URLS_WORKFLOW,
    IDB_ABBREVIATION : SEED_URLS_WORKFLOW,
    IFC_ABBREVIATION : SEED_URLS_WORKFLOW,
    KFW_ABBREVIATION : DOWNLOAD_WORKFLOW,
    MIGA_ABBREVIATION : SEED_URLS_WORKFLOW,
    NBIM_ABBREVIATION : DOWNLOAD_WORKFLOW,
    PRO_ABBREVIATION : SEED_URLS_WORKFLOW,
    UNDP_ABBREVIATION : SEED_URLS_WORKFLOW,
    WB_ABBREVIATION : DOWNLOAD_WORKFLOW
}
