# Generated by Django 3.2.7 on 2023-12-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(blank=True, db_column='complaint_name', max_length=255, null=True)),
                ('complaint_status', models.CharField(blank=True, db_column='complaint_status', max_length=50, null=True)),
                ('complaint_url', models.CharField(blank=True, db_column='complaint_url', max_length=255, null=True)),
                ('filer_name', models.CharField(blank=True, db_column='filer_name', max_length=500, null=True)),
                ('filing_date', models.DateField(db_column='filing_date', max_length=25, null=True)),
                ('is_registered', models.BooleanField(db_column='is_registered', null=True)),
                ('registration_start', models.DateField(db_column='registration_start', null=True)),
                ('registration_end', models.DateField(db_column='registration_end', null=True)),
                ('registration_status', models.TextField(blank=True, db_column='registration_status', null=True)),
                ('no_registration_explanation', models.TextField(blank=True, db_column='no_registration_explanation', null=True)),
                ('issued_registration_report', models.BooleanField(db_column='issued_registration_report', null=True)),
                ('is_eligible', models.BooleanField(db_column='is_eligible', null=True)),
                ('eligibility_start', models.DateField(db_column='eligibility_start', null=True)),
                ('eligibility_end', models.DateField(db_column='eligibility_end', null=True)),
                ('eligibility_status', models.CharField(blank=True, db_column='eligibility_status', max_length=50, null=True)),
                ('no_eligibility_explanation', models.TextField(blank=True, db_column='no_eligibility_explanation', null=True)),
                ('issued_eligibility_report', models.BooleanField(db_column='issued_eligibility_report', null=True)),
                ('dispute_resolution_start', models.DateField(db_column='dispute_resolution_start', null=True)),
                ('dispute_resolution_end', models.DateField(db_column='dispute_resolution_end', null=True)),
                ('dispute_resolution_status', models.CharField(blank=True, db_column='dispute_resolution_status', max_length=50, null=True)),
                ('no_dispute_resolution_explanation', models.TextField(blank=True, db_column='no_dispute_resolution_explanation', null=True)),
                ('issued_dispute_report', models.BooleanField(db_column='issued_dispute_report', null=True)),
                ('is_monitored', models.BooleanField(db_column='is_monitored', null=True)),
                ('monitoring_start', models.DateField(db_column='monitoring_start', null=True)),
                ('monitoring_end', models.DateField(db_column='monitoring_end', null=True)),
                ('monitoring_status', models.CharField(blank=True, db_column='monitoring_status', max_length=50, null=True)),
                ('no_monitoring_explanation', models.TextField(blank=True, db_column='no_monitoring_explanation', null=True)),
                ('issued_monitoring_report', models.BooleanField(db_column='issued_monitoring_report', null=True)),
                ('found_non_compliance', models.BooleanField(db_column='found_non_compliance', null=True)),
                ('issued_compliance_report', models.BooleanField(db_column='issued_compliance_report', null=True)),
                ('compliance_review_start', models.DateField(db_column='compliance_review_start', null=True)),
                ('compliance_review_end', models.DateField(db_column='compliance_review_end', null=True)),
                ('compliance_review_status', models.CharField(blank=True, db_column='compliance_review_status', max_length=50, null=True)),
                ('no_compliance_review_explanation', models.TextField(blank=True, db_column='no_compliance_review_explanation', null=True)),
                ('has_agreement', models.BooleanField(db_column='has_agreement', null=True)),
                ('date_closed', models.DateField(db_column='date_closed', max_length=25, null=True)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'complaint_issue',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_issue_name'),
        ),
        migrations.AddField(
            model_name='complaintissue',
            name='complaint_id',
            field=models.ForeignKey(db_column='complaint_id', on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintissue',
            name='issue_id',
            field=models.ForeignKey(db_column='issue_id', on_delete=django.db.models.deletion.CASCADE, to='complaints.issue'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issues',
            field=models.ManyToManyField(through='complaints.ComplaintIssue', to='complaints.Issue'),
        ),
    ]
