# Generated by Django 3.2.7 on 2023-12-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='complaintissue',
            constraint=models.UniqueConstraint(fields=('complaint_id', 'issue_id'), name='unique_complaint_issue'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('project_id', 'complaint_name', 'complaint_status', 'complaint_url', 'filing_date'), name='unique_complaint'),
        ),
    ]
