# Generated by Django 3.2.7 on 2023-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('abbreviation', models.TextField(db_column='abbreviation')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='IAM',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
            ],
            options={
                'db_table': 'iam',
            },
        ),
        migrations.CreateModel(
            name='BankIAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam_year', models.IntegerField(db_column='iam_year', null=True)),
                ('iam_month', models.IntegerField(db_column='iam_month', null=True)),
                ('iam_day', models.IntegerField(db_column='iam_day', null=True)),
                ('iam_date_notes', models.TextField(db_column='iam_date_notes', null=True)),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, db_column='created_at_utc', null=True)),
                ('bank', models.ForeignKey(db_column='bank', on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
                ('iam', models.ForeignKey(db_column='iam', on_delete=django.db.models.deletion.CASCADE, to='banks.iam')),
            ],
            options={
                'db_table': 'bank_iam',
            },
        ),
    ]
