openapi: 3.0.3
info:
  title: DeBIT API
  version: 1.0.0
  description: Serves development bank investment project and related finance data.
paths:
  /api/banks:
    get:
      operationId: banks_list
      description: Read-only view to list all banks in the database.
      tags:
      - banks
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
          description: ''
  /api/countries:
    get:
      operationId: countries_list
      description: |-
        Read-only view to list simplified country records
        without project relationships or GeoJSON boundaries.
      tags:
      - countries
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryList'
          description: ''
  /api/countries/project-countries:
    post:
      operationId: countries_project_countries_create
      description: |-
        Inserts one or more project-country records into the database.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized, newly-created
                project-country records.
      tags:
      - countries
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/form13f/companies:
    post:
      operationId: form13f_companies_create
      description: |-
        Upserts one or more companies into the database.

        Args:
            request (`Request`): The request object.

        Returns:
            (`JsonResponse`): The list of serialized,
                newly-created companies.
      tags:
      - form13f
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/form13f/forms:
    post:
      operationId: form13f_forms_create
      description: |-
        Upserts one or more submissions into the database.

        Args:
            request (`Request`): The request object.

        Returns:
            (`JsonResponse`): The list of serialized,
                newly-created submissions.
      tags:
      - form13f
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/form13f/investments:
    post:
      operationId: form13f_investments_create
      description: |-
        Inserts one or more investments into the database.

        Args:
            request (`Request`): The request object.

        Returns:
            (`JsonResponse`): The list of serialized,
                newly-created investments.
      tags:
      - form13f
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/form13f/investments/search:
    post:
      operationId: form13f_investments_search_create
      description: |-
        Retrieves a subset of available Form 13F
        investments using a search query.

        Args:
            request (`Request`): The Django REST Framework
                request object.

        Returns:
            (`JsonResponse`): The list of serialized
                investment records.
      tags:
      - form13f
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/pipeline/jobs:
    get:
      operationId: pipeline_jobs_retrieve
      description: |-
        Retrieves all jobs in the database.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of job records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: pipeline_jobs_create
      description: |-
        Inserts a new job into the database.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The newly-created job.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/pipeline/jobs/{job_id}:
    get:
      operationId: pipeline_jobs_retrieve_2
      description: |-
        Retrieves a job by id.

        Args:
            request (`Request`): The Django REST Framework request object.

            job_id (`int`): The job id.

        Returns:
            (`JsonResponse`): The job.
      parameters:
      - in: path
        name: job_id
        schema:
          type: string
        required: true
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    patch:
      operationId: pipeline_jobs_partial_update
      description: |-
        Updates the status of a job in the database.

        Args:
            request (`Request`): The Django REST Framework request object.

            job_id (`int`): The job id.

        Returns:
            (`JsonResponse`): The updated job.
      parameters:
      - in: path
        name: job_id
        schema:
          type: string
        required: true
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/pipeline/staged-investments:
    get:
      operationId: pipeline_staged_investments_retrieve
      description: |-
        Retrieves staged investments from the database table.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized,
                newly-created staged investment records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: pipeline_staged_investments_create
      description: |-
        Inserts one or more staged investment records into the database.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (JsonResponse): The list of serialized, newly-created
                staged investment records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: pipeline_staged_investments_destroy
      description: |-
        Deletes one or more staged investment records from the database.

        Args:
            request (`Request`): The Django REST Framework request object.
                Must contain a list of one or more ids in the request body.

        Returns:
            (`JsonResponse`): A response containing the number of records
                successfully deleted.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/pipeline/staged-projects:
    get:
      operationId: pipeline_staged_projects_retrieve
      description: |-
        Retrieves staged projects from the database table.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized, newly-created
                staged project records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: pipeline_staged_projects_create
      description: |-
        Inserts one or more staged project records into the database.

        Args:
            request (`Request`): The request object.

        Returns:
            (`JsonResponse`): The list of serialized, newly-created
                staged project records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    patch:
      operationId: pipeline_staged_projects_partial_update
      description: |-
        Updates one or more staged project records from the database by id.

        Args:
            request (`Request`): The Django REST Framework request object.
                Must contain a list of one or more ids in the request body.

        Returns:
            (`JsonResponse`): A response containing the number of records
                successfully deleted.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: pipeline_staged_projects_destroy
      description: |-
        Deletes one or more staged project records from the database by id.

        Args:
            request (`Request`): The Django REST Framework request object.
                Must contain a list of one or more ids in the request body.

        Returns:
            (`JsonResponse`): A response containing the number of records
                successfully deleted.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/pipeline/staged-projects/delete-by-url:
    delete:
      operationId: pipeline_staged_projects_delete_by_url_destroy
      description: |-
        Deletes one or more staged project records from the database by url.

        Args:
            request (`Request`): The Django REST Framework request object.
                Must contain a list of one or more ids in the request body.

        Returns:
            (`JsonResponse`): A response containing the number of records
                successfully deleted.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/pipeline/staged-projects/search-by-url:
    post:
      operationId: pipeline_staged_projects_search_by_url_create
      description: |-
        Retrieves staged projects from the database table by url.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized staged project records.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/pipeline/tasks:
    post:
      operationId: pipeline_tasks_create
      description: |-
        Inserts a task into the database, or, using
        a bulk operation, a list of tasks. If the tasks
        already exist in the database, an empty list
        is returned.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The newly-created tasks, if any.
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/pipeline/tasks/{task_id}:
    patch:
      operationId: pipeline_tasks_partial_update
      description: |-
        Updates fields of the task corresponding to the given id.

        Args:
            request (`Request`): The Django REST Framework request object.

            task_id (`int`): The auto-generated primary id for the task.

        Returns:
            (`JsonResponse`): The updated task.
      parameters:
      - in: path
        name: task_id
        schema:
          type: string
        required: true
      tags:
      - pipeline
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/projects:
    post:
      operationId: projects_create
      description: |-
        Inserts or upserts one or more finalized
        project records into the database.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized, newly-created
                staged project records.
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/projects/{id}:
    get:
      operationId: projects_retrieve
      description: REST API operations for single projects.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
  /api/projects/search:
    post:
      operationId: projects_search_create
      description: |-
        Retrieves a subset of available projects
        using a search query.

        Args:
            request (`Request`): The Django REST Framework request object.

        Returns:
            (`JsonResponse`): The list of serialized project records.
      tags:
      - projects
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/sectors:
    get:
      operationId: sectors_list
      description: Read-only view to list all banks in the database.
      tags:
      - sectors
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sector'
          description: ''
  /api/sectors/project-sectors:
    post:
      operationId: sectors_project_sectors_create
      description: |-
        Bulk inserts one or more records into the database
        while ignoring any conflicts that occur.

        Args:
            request (`Request`): The Django REST Framework
                request object.

        Returns:
            (`JsonResponse`): The list of primary keys from
                the newly-created records.
      tags:
      - sectors
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectSector'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProjectSector'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProjectSector'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSector'
          description: ''
components:
  schemas:
    Bank:
      type: object
      description: A serializer for development banks.
      properties:
        id:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        name:
          type: string
        abbreviation:
          type: string
      required:
      - abbreviation
      - id
      - name
    CountryList:
      type: object
      description: A serializer for countries.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        iso_code:
          type: string
      required:
      - id
      - iso_code
      - name
    Project:
      type: object
      description: A serializer for development bank projects.
      properties:
        id:
          type: integer
          readOnly: true
        bank:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        number:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
          maxLength: 50
        year:
          type: integer
          maximum: 32767
          minimum: -32768
          nullable: true
        month:
          type: integer
          maximum: 32767
          minimum: -32768
          nullable: true
        day:
          type: integer
          maximum: 32767
          minimum: -32768
          nullable: true
        loan_amount:
          type: number
          format: double
          nullable: true
        loan_amount_currency:
          type: string
          nullable: true
          maxLength: 50
        loan_amount_in_usd:
          type: number
          format: double
          nullable: true
        sector_list_raw:
          type: string
          nullable: true
        sector_list_stnd:
          type: string
          nullable: true
        companies:
          type: string
          nullable: true
        country_list_raw:
          type: string
          nullable: true
        country_list_stnd:
          type: string
          nullable: true
        url:
          type: string
          nullable: true
      required:
      - bank
      - id
    ProjectSector:
      type: object
      description: A serializer for project-sector associations
      properties:
        project:
          type: integer
        sector:
          type: integer
      required:
      - project
      - sector
    Sector:
      type: object
      description: A serializer for sectors.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
      required:
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
